AllCops:
  RunRailsCops: true

Style/DocumentationMethod:
  RequireForNonPublicMethods: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: when_needed
  SupportedStyles:
    - when_needed
    - always

Style/WhileUntilModifier:
  MaxLineLength: 250
