inherit_from:
  - enabled.yml
  - disabled.yml

AllCops:
  Exclude:
    - db/schema.rb

Style/DocumentationMethod:
  RequireForNonPublicMethods: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: false

Style/LineLength:
  Max: 201

Style/StringLiterals:
  SupportedStyles:
    - single_quotes
    - double_quotes
  ConsistentQuotesInMultiline: false
